### ISSUE TITLE
Training models broke down

### ISSUE THREAD

**Issue by Taikakim** [maxfrenzel/SampleVAE#16]
I have a strange issue... After initially getting SampleVAE to work and after training one 6k model with not so good results, I started training a bigger 140k percussion model. Generating the features went fine, but when I try to train, I get an error:

Also for some reason all new models have now always the default sample defined at 8 seconds in the parameters file, a length that the code does not even support. This is super curious. For the error below, the only changes I've made are changing the sample length parameter back to 2 which it should be. Do you have any idea what could be the issue here? I've npw tried generating several new models, all give the same error. I have Python 3.7.9 installed by hand, as well as Tensorflow 1.13.2, and in any case for the first few days things were working fine.

---

:~/Downloads/SampleVAE-master$ python3.7 train.py --logdir Kim-140k --dataset Perc-AVP
/home/kim/.local/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
/home/kim/.local/lib/python3.7/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
  from numba.decorators import jit as optional_jit
Loading existing parameters.
Kim-140k/params.json
Loading dataset.
Found matching feature directory: ./features/features_1603576082.
100%|████████████████████████████████| 126877/126877 [00:01<00:00, 89642.16it/s]
Features complete.
Generating data index.
100%|█████████████████████████████████| 126877/126877 [00:46<00:00, 2721.43it/s]
Total amount of data:  126877
Feature length:  344
Loading dataset.
Found matching feature directory: ./features/features_1603576082.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14098/14098 [00:00<00:00, 138763.84it/s]
Features complete.
Generating data index.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14098/14098 [00:04<00:00, 2823.16it/s]
Total amount of data:  14098
Num classes:  []
WARNING:tensorflow:From train.py:208: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Creating model.

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /home/kim/.local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Model created.
Setting up loss.
Traceback (most recent call last):
  File "/home/kim/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension size must be evenly divisible by 1568 but is 286720 for 'vae_1/Reshape' (op: 'Reshape') with input shapes: [64,7,20,32], [2] and with input tensors computed as partial shapes: input[1] = [?,1568].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 447, in <module>
    main()
  File "train.py", line 233, in main
    loss, accuracy = net.loss(spec_batch, truth_batch, beta=args.beta)
  File "/home/kim/Downloads/SampleVAE-master/model_iaf.py", line 624, in loss
    output, encoder_mu, encoder_logvar, encoder_std, epsilon, z, nf_sigma, y_prob_list, y_logprob_list = self._create_network(input_batch)
  File "/home/kim/Downloads/SampleVAE-master/model_iaf.py", line 356, in _create_network
    encoder_hidden = tf.reshape(encoder_hidden, [-1, self.conv_out_units])
  File "/home/kim/.local/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7179, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/kim/.local/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/kim/.local/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/kim/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/kim/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/home/kim/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension size must be evenly divisible by 1568 but is 286720 for 'vae_1/Reshape' (op: 'Reshape') with input shapes: [64,7,20,32], [2] and with input tensors computed as partial shapes: input[1] = [?,1568].
`

**Comment by Taikakim** [comment]
Oops, my bad, I had changed the original parameters file in the root, and forgot about it. My bad. Sorry for al the fumbling, this is new to me :P I'm now trying to train a 140k percussion model, but many of the samples do not load, maybe because of bitrate/depth incompability? Now the features code passes random features for them, is this bad for the model?
